import type { ChapterTheme } from "../types";

export interface AssetManifestEntry {
  key: string;
  kind: "sprite" | "tile" | "ui" | "fx";
  width: number;
  height: number;
  replaceWith?: string;
  description: string;
}

export const assetManifest: AssetManifestEntry[] = [
  {
    key: "cursor-hunt-background-large",
    kind: "ui",
    width: 1672,
    height: 941,
    replaceWith: "素材/第一章/背景/cursor-hunt-background-iteration.png",
    description:
      "Chapter 1 runtime background layer. Foreground gameplay platforms and doors are removed so collision can align to the separate foreground layer.",
  },
  {
    key: "cursor-hunt-foreground-large",
    kind: "ui",
    width: 1672,
    height: 941,
    replaceWith: "素材/第一章/前景/cursor-hunt-foreground-large.png",
    description:
      "Chapter 1 transparent foreground layer with platform art, taskbar floor, ladders, pipes, hidden door, vines, and desktop icons aligned to the existing world coordinates.",
  },
  {
    key: "cursor-hunt-desktop-bg",
    kind: "ui",
    width: 1672,
    height: 941,
    replaceWith: "src/assets/chapter1/cursor-hunt-desktop.png",
    description: "第 1 章专属桌面追逐关卡底图，包含图标平台、窗口边缘、任务栏阴影和右下角隐藏门。",
  },
  {
    key: "wrong-gateway-bg",
    kind: "ui",
    width: 2880,
    height: 1080,
    replaceWith: "素材/第二章/背景/wrong-gateway-background-iteration.png",
    description: "第 2 章横向+纵向扩展服务器关卡底图，约三屏宽两屏高，保留暗青色服务器墙、顶部线缆和下层管线空间。",
  },
  {
    key: "wrong-gateway-floor",
    kind: "tile",
    width: 1248,
    height: 48,
    replaceWith: "素材/第二章/地面/wrong-gateway-floor.png",
    description: "第 2 章从参考图裁出的主地面平台条，含黄铜边线和黑色机械底座。",
  },
  {
    key: "wrong-gateway-platform-short",
    kind: "tile",
    width: 132,
    height: 32,
    replaceWith: "素材/第二章/平台/wrong-gateway-platform-short.png",
    description: "第 2 章短悬浮平台素材，从参考图左侧平台裁切。",
  },
  {
    key: "wrong-gateway-platform-long",
    kind: "tile",
    width: 298,
    height: 30,
    replaceWith: "素材/第二章/平台/wrong-gateway-platform-long.png",
    description: "第 2 章长悬浮平台素材，从参考图中部平台裁切。",
  },
  {
    key: "wrong-gateway-platform-hanging",
    kind: "tile",
    width: 82,
    height: 28,
    replaceWith: "素材/第二章/平台/wrong-gateway-platform-hanging.png",
    description: "第 2 章吊挂平台素材，保留参考图链条下方小平台质感。",
  },
  {
    key: "wrong-gateway-ladder",
    kind: "tile",
    width: 72,
    height: 216,
    replaceWith: "素材/第二章/楼梯/wrong-gateway-ladder.png",
    description: "第 2 章楼梯/梯子素材，从参考图主平台左侧裁切。",
  },
  {
    key: "wrong-gateway-digit-base",
    kind: "ui",
    width: 90,
    height: 72,
    replaceWith: "素材/第二章/数字模块/wrong-gateway-digit-base.png",
    description: "第 2 章可撞击数字模块底座，从参考图数字格裁切并擦除数字区域，运行时动态绘制数字。",
  },
  {
    key: "wrong-gateway-separator",
    kind: "ui",
    width: 56,
    height: 54,
    replaceWith: "素材/第二章/数字模块/wrong-gateway-separator.png",
    description: "第 2 章替代 IP 点号的发光分隔符素材，从参考图青色方点组裁切。",
  },
  {
    key: "wrong-gateway-portal",
    kind: "ui",
    width: 424,
    height: 390,
    replaceWith: "素材/第二章/网关/wrong-gateway-portal.png",
    description: "第 2 章右侧错误网关门框和红色传送门裁切素材。",
  },
  {
    key: "wrong-gateway-ip-warning-panel",
    kind: "ui",
    width: 1672,
    height: 941,
    replaceWith: "素材/第二章/提示/wrong-gateway-ip-warning-panel.png",
    description: "第 2 章怪物抓到玩家时弹出的 IP 地址不存在警示面板，匹配错误网关暗青机房与黄铜平台边风格。",
  },
  {
    key: "player-pet",
    kind: "sprite",
    width: 24,
    height: 24,
    description: "第 1-2 章可爱 agent 桌宠占位像素图。",
  },
  {
    key: "player-code",
    kind: "sprite",
    width: 28,
    height: 22,
    description: "第 4 章后深红半透明代码生命体占位像素图。",
  },
  {
    key: "player-clone",
    kind: "sprite",
    width: 22,
    height: 18,
    description: "分身控制能力生成的副本占位像素图。",
  },
  {
    key: "boss-core",
    kind: "sprite",
    width: 72,
    height: 54,
    description: "17 个 Boss 共用核心轮廓，运行时按 Boss 颜色和名称区分。",
  },
  {
    key: "code-block",
    kind: "sprite",
    width: 18,
    height: 18,
    description: "代码块、记忆片段、钥匙碎片和章节收集物占位图。",
  },
  {
    key: "hazard-scan",
    kind: "fx",
    width: 64,
    height: 10,
    description: "鼠标、杀毒扫描、权限墙和声波等危险带占位图。",
  },
  {
    key: "electromagnetic-trap-beam",
    kind: "fx",
    width: 384,
    height: 64,
    replaceWith: "src/assets/hazards/electromagnetic-trap-beam-sheet.png",
    description: "4-frame electromagnetic trap beam spritesheet that can stretch horizontally or rotate for vertical traps.",
  },
  {
    key: "wrong-gateway-shredder",
    kind: "fx",
    width: 768,
    height: 192,
    replaceWith: "src/assets/hazards/wrong-gateway-shredder-sheet.png",
    description: "4-frame animated cyber shredder trap spritesheet used to fill wrong-gateway floor gaps as instant-kill hazards.",
  },
  {
    key: "boss-bullet",
    kind: "fx",
    width: 10,
    height: 10,
    description: "Boss 数据包、加密块、墨水、声波等弹幕占位图。",
  },
  {
    key: "exit-node",
    kind: "ui",
    width: 40,
    height: 48,
    description: "章节出口、网络节点或设备端口占位图。",
  },
  {
    key: "pd-background",
    kind: "tile",
    width: 256,
    height: 256,
    description: "第 3 章粉碎器内壁背景纹理，由回收站器官化机器和代码残影组成。",
  },
  {
    key: "pd-gear",
    kind: "fx",
    width: 96,
    height: 96,
    description: "第 3 章粉碎齿轮危险机关。",
  },
  {
    key: "pd-anchor",
    kind: "fx",
    width: 36,
    height: 36,
    description: "第 3 章触手牵引用红色锚点。",
  },
  {
    key: "pd-process",
    kind: "sprite",
    width: 48,
    height: 40,
    description: "第 3 章清理进程敌人占位图。",
  },
  {
    key: "pd-cache",
    kind: "sprite",
    width: 46,
    height: 40,
    description: "第 3 章可吞噬缓存囊与敌人残骸。",
  },
  {
    key: "pd-file-shell",
    kind: "sprite",
    width: 82,
    height: 52,
    description: "第 3 章可渗透的损坏文件壳藏身点。",
  },
  {
    key: "pd-exit",
    kind: "ui",
    width: 78,
    height: 92,
    description: "第 3 章粉碎器外裂缝出口。",
  },
  {
    key: "code-rebirth-bg",
    kind: "ui",
    width: 1440,
    height: 2560,
    replaceWith: "素材/第三章/背景/code-rebirth-vertical-background-iteration.png",
    description: "Chapter 3 vertical background layer for the code-rebirth route.",
  },
  {
    key: "code-rebirth-fg",
    kind: "ui",
    width: 1440,
    height: 2560,
    replaceWith: "素材/第三章/前景/code-rebirth-vertical-foreground.png",
    description: "Chapter 3 transparent foreground layer aligned to the code-rebirth world.",
  },
  {
    key: "code-rebirth-bottom-platform",
    kind: "ui",
    width: 1440,
    height: 300,
    replaceWith: "素材/第三章/地面/code-rebirth-bottom-platform.png",
    description: "Chapter 3 generated bottom floor platform overlay matching the old vertical code-rebirth artwork.",
  },
  {
    key: "code-rebirth-lifeform",
    kind: "sprite",
    width: 1774,
    height: 887,
    replaceWith: "素材/第三章/主角/code-rebirth-lifeform-generated.png",
    description: "Chapter 3 cyan pixel-code lifeform source sprite; runtime body is procedurally deformed for writhing movement.",
  },
  {
    key: "code-rebirth-worm",
    kind: "sprite",
    width: 88,
    height: 44,
    replaceWith: "素材/第三章/敌人/code-rebirth-mechanical-worm.png",
    description: "Chapter 3 tiny red computer-worm virus enemy sprite.",
  },
  {
    key: "code-rebirth-turret",
    kind: "sprite",
    width: 96,
    height: 80,
    replaceWith: "素材/第三章/机关/code-rebirth-turret.png",
    description: "Chapter 3 small wall-mounted hackable turret sprite.",
  },
  {
    key: "code-rebirth-platform-turret",
    kind: "sprite",
    width: 88,
    height: 72,
    replaceWith: "素材/第三章/机关/code-rebirth-platform-turret.png",
    description: "Chapter 3 small platform-mounted hackable turret sprite.",
  },
  {
    key: "code-rebirth-projectile",
    kind: "fx",
    width: 64,
    height: 32,
    replaceWith: "素材/第三章/特效/code-rebirth-turret-projectile.png",
    description: "Chapter 3 turret projectile effect sprite.",
  },
  {
    key: "code-rebirth-infection-sparks",
    kind: "fx",
    width: 64,
    height: 64,
    replaceWith: "素材/第三章/特效/code-rebirth-infection-sparks.png",
    description: "Chapter 3 turret invasion and control-transfer effect strip.",
  },
  {
    key: "trash-mountain-bg",
    kind: "ui",
    width: 1440,
    height: 2600,
    replaceWith: "素材/第四章/背景/trash-mountain-vertical-background.png",
    description:
      "Chapter 4 vertical background layer with recycle-bin debris, archive cliffs, broken desktop windows, and a dark e-waste shaft.",
  },
  {
    key: "trash-mountain-bg-v2",
    kind: "ui",
    width: 1800,
    height: 1100,
    replaceWith: "素材/第四章/背景/trash-mountain-background-iteration.png",
    description:
      "Chapter 4 wide generated pixel-art background iteration with a recycle-bin basin, archive cliffs, cache bogs, permission shards, shredder ruins, and a cyan My Computer/LAN exit.",
  },
  {
    key: "trash-mountain-fg",
    kind: "ui",
    width: 1440,
    height: 2600,
    replaceWith: "素材/第四章/前景/trash-mountain-vertical-foreground.png",
    description:
      "Chapter 4 transparent foreground atmosphere layer with side debris, dangling cables, code rain, and recycle silhouettes.",
  },
  {
    key: "trash-mountain-platform-shelf",
    kind: "tile",
    width: 768,
    height: 150,
    replaceWith: "素材/第四章/平台/trash-mountain-platform-shelf.png",
    description:
      "Chapter 4 generated floating shelf art made from old window title bars, e-waste, folders, recycle fragments, and hanging cables.",
  },
  {
    key: "trash-mountain-bottom-platform",
    kind: "tile",
    width: 1440,
    height: 260,
    replaceWith: "素材/第四章/地面/trash-mountain-bottom-platform.png",
    description: "Chapter 4 generated bottom garbage-basin platform overlay aligned to the first vertical route collision surface.",
  },
  {
    key: "trash-mountain-my-computer-gate",
    kind: "ui",
    width: 256,
    height: 228,
    replaceWith: "素材/第四章/网关/trash-mountain-my-computer-gate.png",
    description: "Chapter 4 custom exit gate toward My Computer, mixing recycle red edge light with cyan LAN portal light.",
  },
  {
    key: "trash-mountain-gateway-warden",
    kind: "sprite",
    width: 256,
    height: 176,
    replaceWith: "素材/第四章/敌人/trash-mountain-gateway-warden.png",
    description: "Chapter 4 custom gateway-warden boss sprite, a corrupted monitor core with cyan eye and red malware cracks.",
  },
  {
    key: "p-drive-bg",
    kind: "ui",
    width: 2100,
    height: 900,
    replaceWith: "素材/第五章/背景/p-drive-background-iteration.png",
    description:
      "Chapter 5 generated pixel-art LAN transition background with a floating P: shared-drive bridge, sync streams, mapped-drive pillars, device fragments, and a D-drive drop portal.",
  },
  {
    key: "leder-d-drive-bg",
    kind: "ui",
    width: 2100,
    height: 900,
    replaceWith: "素材/第六章/背景/leder-d-drive-background-iteration.png",
    description:
      "Chapter 6 generated pixel-art D-drive background with downloads swamp, project-folder forest, asset-library cave, duplicate maze, search-index web, and the distant C-drive permission wall.",
  },
  {
    key: "c-wall-bg",
    kind: "ui",
    width: 1664,
    height: 960,
    replaceWith: "素材/第七章/背景/c-wall-permission-background-iteration.png",
    description:
      "Chapter 7 clean pixel-art C-drive permission-wall background with large lock architecture, three decryption slots, restrained red cracks, and no speckled particle noise.",
  },
  {
    key: "leder-c-drive-bg",
    kind: "ui",
    width: 2200,
    height: 1000,
    replaceWith: "素材/第八章/背景/leder-c-drive-background-iteration.png",
    description:
      "Chapter 8 clean pixel-art C-drive system-fortress background with Program Files walls, AppData alleys, service pipes, quarantine cells, task-manager lattice, and admin-token gate.",
  },
  {
    key: "router-core-bg",
    kind: "ui",
    width: 2048,
    height: 1024,
    replaceWith: "素材/第九章/背景/router-core-background-iteration.png",
    description:
      "Chapter 9 clean pixel-art router-core background with WAN intake, port matrix, solid NAT circuit paths, firewall-heart chamber, and device fan-out node.",
  },
  {
    key: "nas-graveyard-bg",
    kind: "ui",
    width: 1900,
    height: 900,
    replaceWith: "素材/第十章/背景/nas-graveyard-background-iteration.png",
    description:
      "Chapter 10 clean pixel-art NAS backup-graveyard background with large drive tombs, old-agent archive pods, version-branch structures, and minimal speckle noise.",
  },
  {
    key: "camera-eye-bg",
    kind: "ui",
    width: 1800,
    height: 840,
    replaceWith: "素材/第十一章/背景/camera-eye-background-iteration.png",
    description:
      "Chapter 11 clean pixel-art camera firmware background with lens hardware, sensor brackets, monitor panes, blind spots, and a distant real-room viewport.",
  },
  {
    key: "printer-belly-bg",
    kind: "ui",
    width: 2040,
    height: 900,
    replaceWith: "素材/第十二章/背景/printer-belly-background-iteration.png",
    description:
      "Chapter 12 clean pixel-art printer-belly background with feed rollers, paper belts, inkhead machinery, queue chutes, and controlled paper highlights.",
  },
  {
    key: "speaker-voiceprint-bg",
    kind: "ui",
    width: 1920,
    height: 900,
    replaceWith: "素材/第十三章/背景/speaker-voiceprint-background-iteration.png",
    description:
      "Chapter 13 clean pixel-art smart-speaker chamber background with woofer cone walls, waveform rails, microphone hardware, and organized audio pulses.",
  },
  {
    key: "dev-board-bg",
    kind: "ui",
    width: 1800,
    height: 850,
    replaceWith: "素材/第十四章/背景/dev-board-background-iteration.png",
    description:
      "Chapter 14 clean pixel-art development-board background with GPIO banks, signal traces, motor control shelves, firmware burn light, and grouped solder pads.",
  },
];

export const themeTileKeys: Record<ChapterTheme, string> = {
  desktop: "tile-desktop",
  settings: "tile-settings",
  recycle: "tile-recycle",
  trash: "tile-trash",
  network: "tile-network",
  "d-drive": "tile-d-drive",
  "c-drive": "tile-c-drive",
  router: "tile-router",
  nas: "tile-nas",
  camera: "tile-camera",
  printer: "tile-printer",
  speaker: "tile-speaker",
  hardware: "tile-hardware",
};
