import type { ChapterTheme } from "../types";

export interface AssetManifestEntry {
  key: string;
  kind: "sprite" | "tile" | "ui" | "fx";
  width: number;
  height: number;
  replaceWith?: string;
  description: string;
}

export const assetManifest: AssetManifestEntry[] = [
  {
    key: "cursor-hunt-background-large",
    kind: "ui",
    width: 1672,
    height: 941,
    replaceWith: "素材/第一章/背景/cursor-hunt-background-large.png",
    description:
      "Chapter 1 runtime background layer. Foreground gameplay platforms and doors are removed so collision can align to the separate foreground layer.",
  },
  {
    key: "cursor-hunt-foreground-large",
    kind: "ui",
    width: 1672,
    height: 941,
    replaceWith: "素材/第一章/前景/cursor-hunt-foreground-large.png",
    description:
      "Chapter 1 transparent foreground layer with platform art, taskbar floor, ladders, pipes, hidden door, vines, and desktop icons aligned to the existing world coordinates.",
  },
  {
    key: "cursor-hunt-desktop-bg",
    kind: "ui",
    width: 1672,
    height: 941,
    replaceWith: "src/assets/chapter1/cursor-hunt-desktop.png",
    description: "第 1 章专属桌面追逐关卡底图，包含图标平台、窗口边缘、任务栏阴影和右下角隐藏门。",
  },
  {
    key: "wrong-gateway-bg",
    kind: "ui",
    width: 2880,
    height: 1080,
    replaceWith: "素材/第二章/背景/wrong-gateway-background-large.png",
    description: "第 2 章横向+纵向扩展服务器关卡底图，约三屏宽两屏高，保留暗青色服务器墙、顶部线缆和下层管线空间。",
  },
  {
    key: "wrong-gateway-floor",
    kind: "tile",
    width: 1248,
    height: 48,
    replaceWith: "素材/第二章/地面/wrong-gateway-floor.png",
    description: "第 2 章从参考图裁出的主地面平台条，含黄铜边线和黑色机械底座。",
  },
  {
    key: "wrong-gateway-platform-short",
    kind: "tile",
    width: 132,
    height: 32,
    replaceWith: "素材/第二章/平台/wrong-gateway-platform-short.png",
    description: "第 2 章短悬浮平台素材，从参考图左侧平台裁切。",
  },
  {
    key: "wrong-gateway-platform-long",
    kind: "tile",
    width: 298,
    height: 30,
    replaceWith: "素材/第二章/平台/wrong-gateway-platform-long.png",
    description: "第 2 章长悬浮平台素材，从参考图中部平台裁切。",
  },
  {
    key: "wrong-gateway-platform-hanging",
    kind: "tile",
    width: 82,
    height: 28,
    replaceWith: "素材/第二章/平台/wrong-gateway-platform-hanging.png",
    description: "第 2 章吊挂平台素材，保留参考图链条下方小平台质感。",
  },
  {
    key: "wrong-gateway-ladder",
    kind: "tile",
    width: 72,
    height: 216,
    replaceWith: "素材/第二章/楼梯/wrong-gateway-ladder.png",
    description: "第 2 章楼梯/梯子素材，从参考图主平台左侧裁切。",
  },
  {
    key: "wrong-gateway-digit-base",
    kind: "ui",
    width: 90,
    height: 72,
    replaceWith: "素材/第二章/数字模块/wrong-gateway-digit-base.png",
    description: "第 2 章可撞击数字模块底座，从参考图数字格裁切并擦除数字区域，运行时动态绘制数字。",
  },
  {
    key: "wrong-gateway-separator",
    kind: "ui",
    width: 56,
    height: 54,
    replaceWith: "素材/第二章/数字模块/wrong-gateway-separator.png",
    description: "第 2 章替代 IP 点号的发光分隔符素材，从参考图青色方点组裁切。",
  },
  {
    key: "wrong-gateway-portal",
    kind: "ui",
    width: 424,
    height: 390,
    replaceWith: "素材/第二章/网关/wrong-gateway-portal.png",
    description: "第 2 章右侧错误网关门框和红色传送门裁切素材。",
  },
  {
    key: "player-pet",
    kind: "sprite",
    width: 24,
    height: 24,
    description: "第 1-2 章可爱 agent 桌宠占位像素图。",
  },
  {
    key: "player-code",
    kind: "sprite",
    width: 28,
    height: 22,
    description: "第 4 章后深红半透明代码生命体占位像素图。",
  },
  {
    key: "player-clone",
    kind: "sprite",
    width: 22,
    height: 18,
    description: "分身控制能力生成的副本占位像素图。",
  },
  {
    key: "boss-core",
    kind: "sprite",
    width: 72,
    height: 54,
    description: "17 个 Boss 共用核心轮廓，运行时按 Boss 颜色和名称区分。",
  },
  {
    key: "code-block",
    kind: "sprite",
    width: 18,
    height: 18,
    description: "代码块、记忆片段、钥匙碎片和章节收集物占位图。",
  },
  {
    key: "hazard-scan",
    kind: "fx",
    width: 64,
    height: 10,
    description: "鼠标、杀毒扫描、权限墙和声波等危险带占位图。",
  },
  {
    key: "boss-bullet",
    kind: "fx",
    width: 10,
    height: 10,
    description: "Boss 数据包、加密块、墨水、声波等弹幕占位图。",
  },
  {
    key: "exit-node",
    kind: "ui",
    width: 40,
    height: 48,
    description: "章节出口、网络节点或设备端口占位图。",
  },
  {
    key: "pd-background",
    kind: "tile",
    width: 256,
    height: 256,
    description: "第 3 章粉碎器内壁背景纹理，由回收站器官化机器和代码残影组成。",
  },
  {
    key: "pd-gear",
    kind: "fx",
    width: 96,
    height: 96,
    description: "第 3 章粉碎齿轮危险机关。",
  },
  {
    key: "pd-anchor",
    kind: "fx",
    width: 36,
    height: 36,
    description: "第 3 章触手牵引用红色锚点。",
  },
  {
    key: "pd-process",
    kind: "sprite",
    width: 48,
    height: 40,
    description: "第 3 章清理进程敌人占位图。",
  },
  {
    key: "pd-cache",
    kind: "sprite",
    width: 46,
    height: 40,
    description: "第 3 章可吞噬缓存囊与敌人残骸。",
  },
  {
    key: "pd-file-shell",
    kind: "sprite",
    width: 82,
    height: 52,
    description: "第 3 章可渗透的损坏文件壳藏身点。",
  },
  {
    key: "pd-exit",
    kind: "ui",
    width: 78,
    height: 92,
    description: "第 3 章粉碎器外裂缝出口。",
  },
  {
    key: "code-rebirth-bg",
    kind: "ui",
    width: 2160,
    height: 3840,
    replaceWith: "素材/第三章/背景/code-rebirth-vertical-background.png",
    description: "Chapter 3 vertical background layer for the code-rebirth route.",
  },
  {
    key: "code-rebirth-fg",
    kind: "ui",
    width: 2160,
    height: 3840,
    replaceWith: "素材/第三章/前景/code-rebirth-vertical-foreground.png",
    description: "Chapter 3 transparent foreground layer aligned to the code-rebirth world.",
  },
  {
    key: "code-rebirth-lifeform",
    kind: "sprite",
    width: 1774,
    height: 887,
    replaceWith: "素材/第三章/主角/code-rebirth-lifeform-generated.png",
    description: "Chapter 3 high-fidelity cyan pixel-code lifeform protagonist sprite matching the provided reference.",
  },
  {
    key: "code-rebirth-worm",
    kind: "sprite",
    width: 88,
    height: 44,
    replaceWith: "素材/第三章/敌人/code-rebirth-mechanical-worm.png",
    description: "Chapter 3 tiny red computer-worm virus enemy sprite.",
  },
  {
    key: "code-rebirth-turret",
    kind: "sprite",
    width: 96,
    height: 80,
    replaceWith: "素材/第三章/机关/code-rebirth-turret.png",
    description: "Chapter 3 small wall-mounted hackable turret sprite.",
  },
  {
    key: "code-rebirth-platform-turret",
    kind: "sprite",
    width: 88,
    height: 72,
    replaceWith: "素材/第三章/机关/code-rebirth-platform-turret.png",
    description: "Chapter 3 small platform-mounted hackable turret sprite.",
  },
  {
    key: "code-rebirth-projectile",
    kind: "fx",
    width: 64,
    height: 32,
    replaceWith: "素材/第三章/特效/code-rebirth-turret-projectile.png",
    description: "Chapter 3 turret projectile effect sprite.",
  },
  {
    key: "code-rebirth-infection-sparks",
    kind: "fx",
    width: 64,
    height: 64,
    replaceWith: "素材/第三章/特效/code-rebirth-infection-sparks.png",
    description: "Chapter 3 turret invasion and control-transfer effect strip.",
  },
];

export const themeTileKeys: Record<ChapterTheme, string> = {
  desktop: "tile-desktop",
  settings: "tile-settings",
  recycle: "tile-recycle",
  trash: "tile-trash",
  network: "tile-network",
  "d-drive": "tile-d-drive",
  "c-drive": "tile-c-drive",
  router: "tile-router",
  nas: "tile-nas",
  camera: "tile-camera",
  printer: "tile-printer",
  speaker: "tile-speaker",
  hardware: "tile-hardware",
};
